# Tag this as fpdocker-pipelight:20.04.1-0.X and fpdocker-pipelight:latest

# Build pipelight on ubuntu.
FROM ubuntu:latest AS builder
LABEL stage=builder
# Install the tools required to setup the build environment.
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install --yes wget dpkg-dev devscripts equivs checkinstall
# Fetch the sources.
RUN wget http://ppa.launchpad.net/pipelight/stable/ubuntu/pool/main/p/pipelight-multi/pipelight-multi_0.2.8.2~ubuntu16.04.1.dsc
RUN wget http://ppa.launchpad.net/pipelight/stable/ubuntu/pool/main/p/pipelight-multi/pipelight-multi_0.2.8.2~ubuntu16.04.1.tar.xz
# Extract the sources, and cd there.
RUN dpkg-source -x pipelight-multi_0.2.8.2~ubuntu16.04.1.dsc
WORKDIR /pipelight-multi-0.2.8.2~ubuntu16.04.1
# Install the build-time dependencies.
RUN mk-build-deps -B
RUN DEBIAN_FRONTEND=noninteractive apt-get install --yes ./pipelight-multi-build-deps-depends_0.2.8.2~ubuntu16.04.1_all.deb
# Configure with win64 support and make.
RUN ./configure --wine-path=/opt/wine-staging/bin/wine --with-win64 --win64-cxx=x86_64-w64-mingw32-g++ --win64-flags="-static-libgcc -static-libstdc++ -static" --wine64-path=/opt/wine-staging/bin/wine64
RUN make
# Package as deb.
RUN checkinstall -D --install=no --nodoc -y --pkgname=pipelight-multi --pkglicense=GPL2 --pkgversion=0.2.8.2 --pkgsource="http://ppa.launchpad.net/pipelight/stable/ubuntu/pool/main/p/pipelight-multi/" --requires="libc6 \(\>= 2.14\),libgcc1 \(\>= 1:3.0\),libstdc++6 \(\>= 5.2\),libx11-6,debconf \(\>= 0.5\) \| debconf-2.0,mesa-utils,ttf-mscorefonts-installer,wget,zenity \| kde-baseapps-bin,zenity \| qdbus,wine-staging,bash \(\>= 4.0\),unzip,cabextract,gnupg" --arch=amd64

FROM fpdocker-wine:latest
# Just in case the workdir didn't reset.
WORKDIR /
# Copy the deb from the builder, and install it.
COPY --from=builder /pipelight-multi-0.2.8.2~ubuntu16.04.1/pipelight-multi_0.2.8.2-1_amd64.deb /pipelight-multi_0.2.8.2-1_amd64.deb
RUN DEBIAN_FRONTEND=noninteractive apt-get install --yes ./pipelight-multi_0.2.8.2-1_amd64.deb
# We don't need the deb anymore, delete it.
RUN rm pipelight-multi_0.2.8.2-1_amd64.deb
# Make the plugins for Basilisk.
RUN mkdir -p /usr/lib/mozilla/plugins
RUN pipelight-plugin --create-mozilla-plugins
# Cleanup unneeded packages.
RUN apt-get autoremove
