ARG CURRVERSION="20.04.1-0.5"


# Build all the flash plugin images in one go.
flash-plugin:
    BUILD +flash32.0.0.330
    BUILD +flash11.2.202.644


# Build a flash plugin image. Feature: Flash Plugin v32_0r0_330.
flash32.0.0.330:
    FROM ../+basilisk
    
    # Install dependencies
    RUN apt-get install --yes libnss3 libgtk2.0-0 libcurl4 libcanberra-pulse
    
    # May be overriden at build-time if you want a slightly different version.
    # If you do that, tag it differently.
    ARG FP_URL="https://archive.org/download/flashplayerarchivedversions2/356/fp_32.0.0.330_archive.zip/32_0_r0_330%2Fflashplayer32_0r0_330_linux.x86_64.tar.gz"
    
    # Make a directory for Flash Player to be extracted into.
    RUN mkdir /flash
    # Download and extract Flash Player.
    RUN wget -qO- $FP_URL | tar xz --directory /flash
    
    # Install Flash Player and its plugin to the required dirs.
    RUN cp -r /flash/usr/* /usr/
    RUN cp /flash/libflashplayer.so $MOZ_PLUGIN_PATH/
    
    # Cleanup: delete the extracted directory.
    RUN rm -r /flash
    
    SAVE IMAGE fpdocker-flash32_0r0_330:latest
    SAVE IMAGE fpdocker-flash32_0r0_330:$CURRVERSION


# Build a flash plugin image. Feature: Flash Plugin v11_2r202_644.
flash11.2.202.644:
    FROM ../+basilisk
    
    # Install dependencies
    RUN apt-get install --yes libnss3 libgtk2.0-0 libcurl4 libcanberra-pulse
    
    # May be overriden at build-time if you want a slightly different version.
    # If you do that, tag it differently.
    ARG FP_URL="https://archive.org/download/flashplayerarchivedversions2/downloads/262/fp_11.2.202.644_archive.zip/11_2_r202_644_64bit%2Fflashplayer11_2r202_644_linux.x86_64.tar.gz"
    
    # Make a directory for Flash Player to be extracted into.
    RUN mkdir /flash
    # Download and extract Flash Player.
    RUN wget -qO- $FP_URL | tar xz --directory /flash
    
    # Install Flash Player and its plugin to the required dirs.
    RUN cp -r /flash/usr/* /usr/
    RUN cp /flash/libflashplayer.so $MOZ_PLUGIN_PATH/
    
    # Cleanup: delete the extracted directory.
    RUN rm -r /flash
    
    SAVE IMAGE fpdocker-flash11_2r202_644:latest
    SAVE IMAGE fpdocker-flash11_2r202_644:$CURRVERSION

